


nomeDoHost : ${SERVER_NAME:localhost}
portaDoHost : ${SERVER_PORT:28001}


urlLogin : ${URL_LOGIN_POST:http://localhost:29001/api/login}
urlImagens : ${URL_LOGIN_POST:http://localhost:29001/api/imagens}


server:
  port: ${SERVER_PORT:28001}
  address: 0.0.0.0
  tomcat:
    max-threads: 200

